"""Bootstrap a fresh Home Assistant install for the demo.

Onboards HA non-interactively (creates an admin user, completes the
core_config / analytics / integration steps), generates a long-lived
access token, and writes ``.env`` in the current working directory.

Idempotent:

* If ``.env`` already exists and its token still works, do nothing
  (still ensures MQTT + areas are set up).
* If onboarding is incomplete, do the full flow.
* If onboarding is done but ``.env`` is missing or stale, exit with
  a pointer to wipe HA — re-creating a long-lived token without
  knowing the existing user's password is messy enough that wiping
  is the cleanest path for a demo.

Usage:

    python -m sandcastle_sim.bootstrap

The CLI invokes this via subprocess with ``cwd=<workdir>`` so the
``.env`` lands in the same workdir the simulator and MCP server
read from. ``<workdir>`` is the repo root for editable installs
and ``~/.local/share/sandcastle-sim`` for pip-installed users.
"""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path
from typing import Optional

import httpx
import websockets

HA_URL = "http://localhost:8123"
WS_URL = "ws://localhost:8123/api/websocket"
CLIENT_ID = HA_URL + "/"

DEFAULT_USERNAME = "demo"
DEFAULT_NAME = "Demo Owner"
DEFAULT_PASSWORD = "demo_password_change_me"
DEFAULT_LANGUAGE = "en"
LLT_NAME = "sandcastle-sim"
LLT_LIFESPAN_DAYS = 3650

# Areas the demo expects. Keys match the entity-ID slug convention
# defined in docs/tool-contract.md.
AREAS = [
    ("living_room", "Living Room"),
    ("kitchen", "Kitchen"),
    ("hallway", "Hallway"),
    ("bedroom", "Bedroom"),
    ("bedroom_2", "Bedroom 2"),
    ("bathroom", "Bathroom"),
]

# MQTT broker config. Hostname matches the docker-compose service
# name (HA + mosquitto share a compose network).
MQTT_BROKER_HOST = "mosquitto"
MQTT_BROKER_PORT = 1883


def _env_path() -> Path:
    """Where the .env lands. Resolved at call time so cwd changes are
    picked up — the CLI runs us with cwd=workdir, which is the repo
    root for editable installs and ~/.local/share/sandcastle-sim for
    pip-installed users."""
    return Path.cwd() / ".env"


def _load_env() -> dict[str, str]:
    """Parse the existing .env, if any, into a dict."""
    env_path = _env_path()
    if not env_path.exists():
        return {}
    out: dict[str, str] = {}
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        out[key.strip()] = val.strip().strip('"').strip("'")
    return out


def _write_env(values: dict[str, str]) -> None:
    """Write a minimal .env file in the current working directory."""
    env_path = _env_path()
    lines = [
        "# Auto-generated by sandcastle_sim.bootstrap — do not commit.",
        f"HA_URL={values['HA_URL']}",
        f"HA_TOKEN={values['HA_TOKEN']}",
        f"HA_USERNAME={values.get('HA_USERNAME', DEFAULT_USERNAME)}",
        f"HA_PASSWORD={values.get('HA_PASSWORD', DEFAULT_PASSWORD)}",
        "MCP_URL=http://localhost:8765/mcp/",
    ]
    env_path.write_text("\n".join(lines) + "\n")
    env_path.chmod(0o600)
    print(f"Wrote {env_path}")


def _token_is_valid(client: httpx.Client, token: str) -> bool:
    """Hit /api/ with the token; 200 means it works."""
    try:
        r = client.get(
            HA_URL + "/api/",
            headers={"Authorization": f"Bearer {token}"},
            timeout=5,
        )
        return r.status_code == 200
    except httpx.HTTPError:
        return False


def _onboarding_state(client: httpx.Client) -> list[dict]:
    r = client.get(HA_URL + "/api/onboarding", timeout=10)
    r.raise_for_status()
    return r.json()


def _create_user(client: httpx.Client) -> str:
    """POST /api/onboarding/users -> auth_code."""
    r = client.post(
        HA_URL + "/api/onboarding/users",
        json={
            "client_id": CLIENT_ID,
            "name": DEFAULT_NAME,
            "username": DEFAULT_USERNAME,
            "password": DEFAULT_PASSWORD,
            "language": DEFAULT_LANGUAGE,
        },
        timeout=15,
    )
    r.raise_for_status()
    body = r.json()
    auth_code = body.get("auth_code")
    if not auth_code:
        raise RuntimeError(f"onboarding/users returned no auth_code: {body!r}")
    return auth_code


def _exchange_auth_code(client: httpx.Client, auth_code: str) -> str:
    """POST /auth/token grant_type=authorization_code -> access_token."""
    r = client.post(
        HA_URL + "/auth/token",
        data={
            "grant_type": "authorization_code",
            "code": auth_code,
            "client_id": CLIENT_ID,
        },
        timeout=15,
    )
    r.raise_for_status()
    body = r.json()
    token = body.get("access_token")
    if not token:
        raise RuntimeError(f"/auth/token returned no access_token: {body!r}")
    return token


def _complete_onboarding(client: httpx.Client, access_token: str) -> None:
    """Mark the remaining steps done so HA's UI doesn't relaunch the
    onboarding wizard. The MCP server doesn't care, but a tidy HA UI
    helps when debugging by hand."""
    headers = {"Authorization": f"Bearer {access_token}"}
    for step in ("core_config", "analytics"):
        path = f"/api/onboarding/{step}"
        r = client.post(HA_URL + path, json={}, headers=headers, timeout=15)
        if r.status_code not in (200, 400):  # 400 = already done
            print(f"  warning: {path} -> {r.status_code} {r.text[:200]}")
        else:
            print(f"  {path} OK ({r.status_code})")

    # The integration step expects client_id + redirect_uri so HA can
    # create an oauth2 client entry for the demo. Failure is non-fatal
    # — onboarding gets stuck on the UI but everything else still
    # works.
    r = client.post(
        HA_URL + "/api/onboarding/integration",
        json={"client_id": CLIENT_ID, "redirect_uri": CLIENT_ID},
        headers=headers,
        timeout=15,
    )
    if r.status_code != 200:
        print(f"  warning: /api/onboarding/integration -> {r.status_code}")
    else:
        print("  /api/onboarding/integration OK")


def _setup_mqtt_integration(client: httpx.Client, token: str) -> bool:
    """Create the MQTT config entry via the config-flow API.

    Modern HA (2024.x+) doesn't accept yaml MQTT config — broker
    settings come through the integration's config flow. We probe
    for an existing entry first so re-runs are no-ops.

    Returns True if MQTT is set up after this call (whether by us or
    pre-existing).
    """
    headers = {"Authorization": f"Bearer {token}"}

    # Already configured? (Re-runs.)
    r = client.get(
        HA_URL + "/api/config/config_entries/entry?domain=mqtt",
        headers=headers,
        timeout=10,
    )
    if r.status_code == 200 and r.json():
        print("  MQTT integration already configured.")
        return True

    r = client.post(
        HA_URL + "/api/config/config_entries/flow",
        json={"handler": "mqtt", "show_advanced_options": True},
        headers=headers,
        timeout=15,
    )
    r.raise_for_status()
    flow = r.json()
    if flow.get("type") != "form" or flow.get("step_id") != "broker":
        raise RuntimeError(f"unexpected MQTT flow shape: {flow!r}")
    flow_id = flow["flow_id"]

    r = client.post(
        HA_URL + f"/api/config/config_entries/flow/{flow_id}",
        json={"broker": MQTT_BROKER_HOST, "port": MQTT_BROKER_PORT},
        headers=headers,
        timeout=15,
    )
    r.raise_for_status()
    body = r.json()
    if body.get("type") != "create_entry":
        raise RuntimeError(f"MQTT flow did not create entry: {body!r}")
    print(f"  MQTT integration created (entry_id={body['result']['entry_id']}).")
    return True


async def _create_areas(token: str) -> None:
    """Create the six demo areas via the WS API.

    The HTTP API doesn't expose area creation cleanly; the WS API
    does (`config/area_registry/list` + `.../create`). Idempotent:
    we list existing first and only create the missing ones.
    """
    async with websockets.connect(WS_URL) as ws:
        hello = json.loads(await ws.recv())
        if hello.get("type") != "auth_required":
            raise RuntimeError(f"unexpected first WS msg: {hello!r}")
        await ws.send(json.dumps({"type": "auth", "access_token": token}))
        ack = json.loads(await ws.recv())
        if ack.get("type") != "auth_ok":
            raise RuntimeError(f"WS auth failed: {ack!r}")

        msg_id = 0

        async def call(payload: dict) -> dict:
            nonlocal msg_id
            msg_id += 1
            payload = {**payload, "id": msg_id}
            await ws.send(json.dumps(payload))
            while True:
                resp = json.loads(await ws.recv())
                if resp.get("id") == msg_id:
                    return resp

        existing = await call({"type": "config/area_registry/list"})
        if not existing.get("success"):
            raise RuntimeError(f"area_registry/list failed: {existing!r}")
        existing_ids = {a["area_id"] for a in existing.get("result", [])}

        for area_id, name in AREAS:
            if area_id in existing_ids:
                print(f"  area '{area_id}' already exists.")
                continue
            resp = await call({
                "type": "config/area_registry/create",
                "area_id": area_id,
                "name": name,
            })
            if not resp.get("success"):
                resp = await call({
                    "type": "config/area_registry/create",
                    "name": name,
                })
                if not resp.get("success"):
                    print(f"  warning: failed to create area '{name}': {resp!r}")
                    continue
            print(f"  created area '{area_id}' ({name})")


async def _create_long_lived_token(access_token: str) -> str:
    """Create a long-lived access token via the WS API."""
    async with websockets.connect(WS_URL) as ws:
        hello = json.loads(await ws.recv())
        if hello.get("type") != "auth_required":
            raise RuntimeError(f"unexpected first WS msg: {hello!r}")

        await ws.send(json.dumps({"type": "auth", "access_token": access_token}))
        ack = json.loads(await ws.recv())
        if ack.get("type") != "auth_ok":
            raise RuntimeError(f"WS auth failed: {ack!r}")

        await ws.send(json.dumps({
            "id": 1,
            "type": "auth/long_lived_access_token",
            "client_name": LLT_NAME,
            "lifespan": LLT_LIFESPAN_DAYS,
        }))
        result = json.loads(await ws.recv())
        if not result.get("success"):
            raise RuntimeError(f"LLT create failed: {result!r}")
        token = result["result"]
        if not isinstance(token, str) or not token:
            raise RuntimeError(f"LLT create returned no token: {result!r}")
        return token


def _bootstrap(force: bool = False) -> int:
    env_path = _env_path()
    with httpx.Client() as client:
        existing = _load_env()

        if not force and existing.get("HA_TOKEN") and _token_is_valid(
            client, existing["HA_TOKEN"]
        ):
            print(f"{env_path} already has a working HA_TOKEN.")
            print("Ensuring MQTT integration + areas are set up ...")
            _setup_mqtt_integration(client, existing["HA_TOKEN"])
            asyncio.run(_create_areas(existing["HA_TOKEN"]))
            print("Done.")
            return 0

        state = _onboarding_state(client)
        user_done = next((s["done"] for s in state if s["step"] == "user"), False)
        print(f"HA onboarding state: {state}")

        if user_done:
            print(
                "Onboarding has already created an admin user, but no usable "
                f"HA_TOKEN was found in {env_path}.\n"
                "HA's persisted state has drifted out of sync with the .env "
                "token. Wipe it and start fresh:\n"
                "  sandcastle-sim reset --yes && sandcastle-sim start"
            )
            return 1

        print("Creating admin user via /api/onboarding/users ...")
        auth_code = _create_user(client)
        print("  got auth_code")

        access_token = _exchange_auth_code(client, auth_code)
        print("  exchanged for short-lived access_token")

        print("Completing remaining onboarding steps ...")
        _complete_onboarding(client, access_token)

        print("Creating long-lived access token via WebSocket ...")
        long_lived = asyncio.run(_create_long_lived_token(access_token))
        print(f"  got LLT (len={len(long_lived)})")

        print("Setting up MQTT integration via config-flow API ...")
        _setup_mqtt_integration(client, long_lived)

        print("Creating areas via WebSocket ...")
        asyncio.run(_create_areas(long_lived))

        _write_env({
            "HA_URL": HA_URL,
            "HA_TOKEN": long_lived,
            "HA_USERNAME": DEFAULT_USERNAME,
            "HA_PASSWORD": DEFAULT_PASSWORD,
        })
        print("Bootstrap complete.")
        return 0


def main(argv: Optional[list[str]] = None) -> int:
    if argv is None:
        argv = sys.argv[1:]
    force = "--force" in argv
    try:
        return _bootstrap(force=force)
    except httpx.HTTPStatusError as exc:
        print(
            f"HTTP error: {exc.response.status_code} on "
            f"{exc.request.method} {exc.request.url}\n"
            f"  body: {exc.response.text[:500]}"
        )
        return 1
    except Exception as exc:
        print(f"Bootstrap failed: {exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
